# Usa imagen oficial de Python
FROM python:3.12-slim

WORKDIR /app

# Instala dependencias
COPY ./requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copia el código
COPY ModuloGetData/mongo_client.py .
COPY ModuloGetData/GetReviews.py .

# Comando para ejecutar el extractor
CMD ["python", "__main__.py"]
